# Generated by Django 2.2.5 on 2020-05-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complaintapp', '0005_complaintinfo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintinfo',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
